name: Build and Push alpine docker image
on:
  pull_request:
    branches: master
  push:
    paths:
      - 'alpine/**'
    branches:
      - '*'
    tags:
      - v*
  schedule:
    - cron: 10 16 * * *

env:
  # 设置 docker 镜像名
  IMAGE_NAME: alpine

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # 构建镜像，指定镜像名
    - name: Build image
      run: docker build . --file alpine/Dockerfile --tag $IMAGE_NAME

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
        run: |
          IMAGE_ID=CruiseTian/$IMAGE_NAME

          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION